library(dplyr)
mechacar_mpg<-read.csv("MechaCar_mpg.csv",check.names = F,stringsAsFactors = F)
lm(vehicle_length ~ vehicle_weight + spoiler_angle + ground_clearance + AWD + mpg, data=mechacar_mpg)
summary(lm(vehicle_length ~ vehicle_weight + spoiler_angle + ground_clearance + AWD + mpg, data=mechacar_mpg))
library(tidyverse)
Suspension_Coil<-read.csv("Suspension_Coil.csv",check.names = F,stringsAsFactors = F)
total_summary<-Suspension_Coil%>%summarise(Mean=mean(PSI),Median=median(PSI),Varience=var(PSI),SD=sd(PSI))
lot_summary<-Suspension_Coil%>%group_by(Manufacturing_Lot)%>%summarise(Mean=mean(PSI),Median=median(PSI),Varience=var(PSI),SD=sd(PSI))
t.test(Suspension_Coil$PSI,mu=1500)
t.test(subset(Suspension_Coil,Manufacturing_Lot=="Lot1",select = PSI),mu=1500)
t.test(subset(Suspension_Coil,Manufacturing_Lot=="Lot2",select = PSI),mu=1500)
t.test(subset(Suspension_Coil,Manufacturing_Lot=="Lot3",select = PSI),mu=1500)
